---
title: "sarg_assays_results_plots"
format: html
editor: visual
---

# summary table (96h)

```{r}
bb_sarg96_mod |>  
  as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |>
  exp() |> # log-odds ratio (crosses 1 = valid)
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1))
# no interaction effect
```

-   no interaction term

# plot beta binom model

```{r}
p_sarg_assay_96 <- 
bb_sarg96_mod |> 
emmeans(~ Depth_band *
          Treatment,
        type = "link") |> 
  gather_emmeans_draws() |> 
  mutate(prob = plogis(.value),
         percentage = prob * 100) |> 
  dplyr::select(-.chain,
                -.iteration,
                -.draw,
                -.value) |> 
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl = ~mean(.x < 1),
                  Pg = ~mean(.x > 1)) |> 
  filter(variable == "percentage") |> 
  ggplot(aes(x = Depth_band,
             y = median,
             fill = Treatment)) +
  geom_pointrange(aes(ymin = lower, 
                      ymax = upper),
                  position = position_dodge(0.25),
                  shape = 21,
                  size = 1,
                  fatten = 3) +
  scale_y_continuous(expression(italic(Sargassum)~loss~("%")),
                     limits = c(0,100),
                     breaks = seq(0, 100, by = 25)) +
  scale_x_discrete(name = "Depth band") +
  theme_classic() +
  ggtitle("Deployment duration: 96h") +
  scale_fill_manual(values = c("#DDD487", "#8AA17D")) +
  theme(axis.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 18),
        legend.position = "none")
```

# pairwise

```{r}
#coral_mod_pairs <- 
bb_sarg96_mod|> 
emmeans(~ Depth_band,
        type = "link") |>
  pairs() |> 
  gather_emmeans_draws() |> # log-odds ratio
  mutate(.value = exp(.value)) |>    
  summarise(median_hdci(.value),
            Pl = mean(.value < 1),
            Pg = mean(.value > 1)) #,
            #.width = c(0.85, 0.95))
```

# summary table (3h)

```{r}
bb_sarg3h_mod |>  
  as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |>
  exp() |> # log-odds ratio (crosses 1 = valid)
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1))

# interaction term
```

# plot binom model

```{r}
p_sarg_assay_3h <- 
bb_sarg3h_mod |> 
emmeans(~ Depth_band *
          Treatment,
        type = "link") |> 
  gather_emmeans_draws() |> 
  mutate(prob = plogis(.value),
         percentage = prob * 100) |> 
  dplyr::select(-.chain,
                -.iteration,
                -.draw,
                -.value) |> 
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl = ~mean(.x < 1),
                  Pg = ~mean(.x > 1)) |> 
  filter(variable == "percentage") |> 
  ggplot(aes(x = Depth_band,
             y = median,
             fill = Treatment)) +
  geom_pointrange(aes(ymin = lower, 
                      ymax = upper),
                  position = position_dodge(0.25),
                  shape = 21,
                  size = 1,
                  fatten = 3) +
  scale_y_continuous(expression(italic(Sargassum)~loss~("%")),
                     limits = c(0,100),
                     breaks = seq(0, 100, by = 25)) +
   geom_image(data = tibble(Depth_band = 4.1,
                           median = 80,
                           Treatment = "Caged"),
             aes(image = "sargassum-spp.png"),
             size = 0.30) + 
  theme_classic() +
  ggtitle("Deployment duration: 3h") +
  scale_fill_manual(values = c("#DDD487", "#8AA17D")) +
  theme(axis.title.y = element_text(size = 15),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 15))
```

# pairwise

```{r}
bb_sarg3h_mod |> 
emmeans(~ Treatment |
          Depth_band,
        type = "link") |>
  pairs() |> 
  gather_emmeans_draws() |> # odds-ratio
  mutate(.value = exp(.value)) |> # log odds-ratio  
  summarise(median_hdci(.value),
            Pl = mean(.value < 1),
            Pg = mean(.value > 1))
```

```{r}
bb_sarg3h_mod |> 
emmeans(~ 
          Depth_band,
        type = "link") |>
  pairs() |> 
  gather_emmeans_draws() |> # odds-ratio
  mutate(.value = exp(.value)) |> # log odds-ratio  
  summarise(median_hdci(.value),
            Pl = mean(.value < 1),
            Pg = mean(.value > 1))
```


# combine plots

```{r}
p_sarg_assay <- 
p_sarg_assay_3h / 
p_sarg_assay_96 +
  plot_annotation(tag_levels = "a") &
  theme(plot.tag = element_text(size = 15))
```

```{r}
ggsave("Fig. 4. sarg_assays.jpeg",
       plot = p_sarg_assay, 
       dpi = 600, 
       height = 8, 
       width = 8, 
       units = "in")
```