---
title: "bites_results_plots"
format: html
editor: visual
---

# NASO UNICORNIS

# summary

```{r}
 nu_mod_hurdle |>  
  as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |>
  exp() |> 
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1))
```

# newdata for NU

```{r}
nu_nd <- 
  nu_mod_hurdle |> 
  emmeans(~ Depth_band,
          type = "link") |> 
  gather_emmeans_draws() |> 
  mutate(Exp_bites = exp(.value)) |> 
  dplyr::select(-.chain,
                -.iteration,
                -.value) |> 
  summarise_draws(median, 
                  HDInterval::hdi) |> 
  as.data.frame()
```


# correct values for Nu: 0 for 20m since no observation at 20m

```{r}
nu_nd <- 
nu_nd |> 
  rows_delete(tibble(Depth_band = "20m")) |> 
  add_row(Depth_band = "20m",
           variable = "Exp_bites", 
           median = 0,
           lower = 0,
           upper = 0) |> 
  mutate(
         Depth_band = factor(Depth_band,
                             levels = c("10m",
                                        "20m",
                                        "30m",
                                        "50m")))
```


# plot Nu

```{r}
p_bites_nu <-
nu_nd |> 
  ggplot(aes(x = Depth_band,
             y = median)) +
  geom_pointrange(aes(ymin = lower,
                      ymax = upper),
                  shape = 21,
                  size = 1,
                  fatten = 3,
                  color = "#929FBD",
                  fill = "#929FBD") +
  scale_y_continuous(name = "Number of bites (3h)",
                     limits = c(0, 250),
                     breaks = seq(0, 250, by = 50)) +
  #scale_x_discrete(name = "") +
  theme_classic() +
    ggtitle(expression(italic(Naso~unicornis))) +
     theme(axis.title.x = element_blank(),
           axis.text.x = element_blank(),
           axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 15),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 18)) +
  geom_image(data = tibble(Depth_band = 4.2,
                           median = 240),
             aes(image = "naso-unicornis-bluespine-unicornfish.png"),
             size = 0.30)
```

# NASO LITURATUS

# summary

```{r}
 nl_mod_hurdle |>  
  as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |>
  exp() |> 
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1))
```

# newdata for NU

```{r}
nl_nd <- 
  nl_mod_hurdle |> 
  emmeans(~ Depth_band,
          type = "link") |> 
  gather_emmeans_draws() |> 
  mutate(Exp_bites = exp(.value)) |> 
  dplyr::select(-.chain,
                -.iteration,
                -.value) |> 
  summarise_draws(median, 
                  HDInterval::hdi) |> 
  as.data.frame()
```

# correct values for Nl: 0 for 30m since no observation at 30m

```{r}
nl_nd <- 
nl_nd |> 
  rows_delete(tibble(Depth_band = "30m")) |> 
  add_row(Depth_band = "30m",
           variable = "Exp_bites", 
           median = 0,
           lower = 0,
           upper = 0) |> 
  mutate(
         Depth_band = factor(Depth_band,
                             levels = c("10m",
                                        "20m",
                                        "30m",
                                        "50m")))
```

# plot Nu

```{r}
p_bites_nl <-
nl_nd |> 
  ggplot(aes(x = Depth_band,
             y = median)) +
  geom_pointrange(aes(ymin = lower,
                      ymax = upper),
                  shape = 21,
                  size = 1,
                  fatten = 3,
                  color = "#DDD487",
                  fill = "#DDD487") +
  scale_y_continuous(name = "Number of bites (3h)",
                     limits = c(0, 250),
                     breaks = seq(0, 250, by = 50)) +
  #scale_x_discrete(name = "") +
  theme_classic() +
    ggtitle(expression(italic(Naso~lituratus))) +
     theme(axis.title.x = element_blank(),
           axis.text.x = element_blank(),
           axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 15),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 18)) +
  geom_image(data = tibble(Depth_band = 4.3,
                           median = 248),
             aes(image = "naso-lituratus-naso-tang.png"),
             size = 0.30)
```

# combine plots

```{r}
p_bites <- 
  p_bites_nl /
  p_bites_nu + plot_annotation(tag_levels = "a")
```

# ggsave 

```{r}
ggsave("Fig. 5. bites.jpeg",
       plot =p_bites, 
       dpi = 600, 
       height = 8, 
       width = 8, 
       units = "in")
```