---
title: "Length_results_plots"
format: html
editor: visual
---

# Description

This qmd explores the model from the "fits" qmd and subsequently visualizes the results.

## load model

```{r}
load("Model_Output/log_length_mod.Rdata")
```

# LENGTH MODEL

# summary table

```{r}
log_length_mod |> as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |> 
  exp() |> 
  summarise_draws(median,
                  HDInterval::hdi,
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1)) |> 
  filter(Pl > 0.85 | 
           Pg > 0.85)
```

# newdata for length plotting

```{r}
log_length_nd <- 
  log_length_mod |> 
  emmeans(~ Depth_band, 
          type = "link") |> 
  gather_emmeans_draws() |> 
  mutate(Exp_length = exp(.value)) |> 
  dplyr::select(-.chain,
                -.iteration,
                -.value) |> 
  summarise_draws(median, 
                  HDInterval::hdi) |> 
  as.data.frame()
```

# pairwise for length among depth bands

```{r}
log_length_mod |> 
emmeans(~ Depth_band,
        type = "link") |>
  pairs(reverse = TRUE) |> 
  gather_emmeans_draws() |> # odds-ratio
  mutate(.value = exp(.value)) |> # log odds-ratio  
  summarise(median_hdci(.value),
            Pl = mean(.value < 1),
            Pg = mean(.value > 1))
```

# plot length

```{r}
p_brow_length <- 
log_length_nd |> 
  mutate(Depth_band = recode(Depth_band,
                             "10m" = "0-10m",
                             "20m" = "11-20m",
                             "30m" = "31-40m",
                             "50m" = "41-50m")) |> 
  ggplot(aes(x = Depth_band,
             y = median)) +
  geom_pointrange(aes(ymin = lower,
                      ymax = upper),
                  shape = 21,
                  size = 1.5,
                  fatten = 3,
                  color = "black",
                  fill = "blue") +
  scale_y_continuous(name = "Total length (cm)",
                     limits = c(0, 50),
                     breaks = seq(0, 50, by = 10)) +
  scale_x_discrete(name = "Depth bands") +
  theme_classic() +
    #ggtitle("Total herbivores") +
     theme(
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        plot.title = element_text(size = 18))
```

# COMBINE: abundance and length plots

```{r}
p_abun_biom <- 
p_brow_abun / p_brow_length +
  plot_annotation(tag_levels = list(c("A)", "B)"))) &
  theme(plot.tag = element_text(size = 15))
```

## ggsave

```{r}
ggsave("Plot/Fig X_MaxN_length.jpeg",
       plot =p_abun_biom, 
       dpi = 600, 
       height = 8, 
       width = 8, 
       units = "in")
```

### end
